### PR TITLE
Added ERD information

### PR DESCRIPTION
**Pull request by wenew2000**
Hi 
Thank you!

### CODE REVIEW

**Comment by erdavenport** [comment]
You're welcome! :)

**Comment by erdavenport** [comment]
Just so you know, you must have set your upstream to my erd-test branch rather than erdavenport. This pull request will show up on erd-test/forkme but not erdavenport/forkme (unless you create a new remote connection to erdavenport/forkme and issue another pull request to there). If you want to do this and need help, come find me after lunch!

**Comment by wenew2000** [comment]
Just saw the message. I also realized that after I sent the pull request. I may try to redo that after the workshop. Thanks,

**Comment by erdavenport** [comment]
Sounds good. Don't hesitate to ask any questions if you get stuck!

**Pull request merged**
